{
  "headers": {
    "listenerpath": "test",
    "method": "post",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.26.8",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "7eb75578-8178-44b2-ae92-11dc25fa9b67",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "29"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/munit",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": null,
  "listenerPath": "/munit",
  "relativePath": "/munit",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/munit",
  "rawRequestPath": "/munit",
  "remoteAddress": "/127.0.0.1:55505",
  "requestPath": "/munit"
}